### PR TITLE
Add default images

### LINKED ISSUE #45: Display service catalog fail if image is not set
Images are not compulsory when adding a new service but sQuest crash when we list services

### PR DESCRIPTION
**Pull request by a-belhadj**
Fix #45

### CODE REVIEW

**Comment by a-belhadj** [comment]
image

**Comment by Sispheor** [comment]
The image need to be placed in "project-static/squest/img" folder.

**Comment by Sispheor** [comment]
@a-belhadj , the right place is [here](https://github.com/HewlettPackard/squest/tree/master/project-static/squest/img)

**Comment by a-belhadj** [comment]
> 
> 
> @a-belhadj , the right place is [here](https://github.com/HewlettPackard/squest/tree/master/project-static/squest/img)

Done

**Pull request merged**
